### ISSUE TITLE
No permissions are showing for Elasticsearch DA

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-icd-elasticsearch#127]
No permissions are showing for Elasticsearch DA. Please ensure that the CRNs are correct in ibm_catalog.json
![image](https://github.com/terraform-ibm-modules/terraform-ibm-icd-elasticsearch/assets/29608224/980c453c-c9b5-455e-89a6-6fdb1f0bd513)

**Comment by Aayush-Abhyarthi** [comment]
https://github.com/terraform-ibm-modules/terraform-ibm-icd-elasticsearch/pull/129
