### ISSUE TITLE
No valid category tag added for Elasticsearch DA

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-icd-elasticsearch#128]
![image](https://github.com/terraform-ibm-modules/terraform-ibm-icd-elasticsearch/assets/29608224/d4f2083e-887e-45ef-aad2-4ec4d05fe85d)

There needs to be a valid category tag added in ibm_catalog.json. For list of valid tags, you can run `ibmcloud catalog filter options --all`

Looks like `databases` needs to be updated to `database`:
![image](https://github.com/terraform-ibm-modules/terraform-ibm-icd-elasticsearch/assets/29608224/6dea9c7f-ae1d-49a3-89b7-599ddfb7895a)

**Comment by Aayush-Abhyarthi** [comment]
https://github.com/terraform-ibm-modules/terraform-ibm-icd-elasticsearch/pull/129
