### ISSUE TITLE
Include configuration for vector database

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-icd-elasticsearch#145]
< Placeholder for now > details to come

**Comment by Aayush-Abhyarthi** [comment]
Any details on what needs to be done here?

**Comment by vburckhardt** [comment]
@Aayush-Abhyarthi - See how to enable vector search from the module/DA. Initial starting point: https://cloud.ibm.com/docs/databases-for-elasticsearch?topic=databases-for-elasticsearch-elser-embeddings-elasticsearch#elser-embeddings-elasticsearch-create-index

**Comment by Aayush-Abhyarthi** [comment]
Seems that it needs a series of commands (shell script) to run after deploying the elastic search. So, are these commands needed to be added as part of the elasticsearch module (or DA) ?

**Comment by daniel-butler-irl** [comment]
These should be done in the module and add a flag to enable it.

**Comment by vburckhardt** [comment]
Module - but use the restapi provider if possible. The documented commands simply invoke the APIs.

**Comment by Aayush-Abhyarthi** [comment]
Status on this issue - Currently working on establishing a connection (with ssl certificate validation) to the elasticsearch instance via CLI and terraform. The documentation uses the curl command which ignores the ssl certificate validation.
