### ISSUE TITLE
DA is missing catalog types

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-icd-elasticsearch#168]
At first glance, but not exclusively:
- region
- plan (can only be enterprise or platinum)

**Comment by ocofaigh** [comment]
I also suggest we mark `var.existing_kms_key_crn` as required in the ibm_catalog.json like we did for other DAs so it shows in the required tab in projects

**Comment by iamar7** [comment]
PR Merged
