### ISSUE TITLE
8.12 is prefered by ICD stack but DA only allows up to 8.10

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-icd-elasticsearch#170]
2024/05/27 13:26:53 Terraform plan |   on ../../modules/fscloud/main.tf line 8, in module "elasticsearch":
 2024/05/27 13:26:53 Terraform plan |    8:   elasticsearch_version         = var.elasticsearch_version
 2024/05/27 13:26:53 Terraform plan |     ├────────────────
 2024/05/27 13:26:53 Terraform plan |     │ var.elasticsearch_version is "8.12"
 2024/05/27 13:26:53 Terraform plan | 
 2024/05/27 13:26:53 Terraform plan | Version must be 8.7 or 8.10 (Enterprise plan only or Platinum if 8.10 or
 2024/05/27 13:26:53 Terraform plan | above). If no value passed, the current ICD preferred version is used.
 2024/05/27 13:26:53 Terraform plan |

**Comment by shemau** [comment]
Implemented in 1.10.12, which also removes 8.7 since this is deprecated and no longer supported for new deployments in many MZRs.
