### ISSUE TITLE
cost usage estamate is incorrect

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-icd-elasticsearch#174]
![image](https://github.com/terraform-ibm-modules/terraform-ibm-icd-elasticsearch/assets/16447795/8882ec84-c71f-4452-b0e0-760b0f682d1e)

**Comment by ocofaigh** [comment]
Issue has been created internally with cost estimation team

**Comment by ocofaigh** [comment]
This has been fixed - closing
