### ISSUE TITLE
Programmatically determine the `kms_region` from the CRN

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-icd-elasticsearch#189]
To be consistent with other DAs, the [DA](https://github.com/terraform-ibm-modules/terraform-ibm-icd-elasticsearch/tree/main/solutions/secure) should ask for:

- `existing_kms_instance_crn` (instead of `existing_kms_instance_guid`)
- Parse the KMS GUID from `existing_kms_instance_crn`
- Parse the KMS region from `existing_kms_instance_crn` and remove the `kms_region` variable

**Comment by Soaib024** [comment]
PR merged - hence closing the issue
