### ISSUE TITLE
New Hosting Model, Investigate if any action needed in the module

### ISSUE THREAD

**Issue by daniel-butler-irl** [terraform-ibm-modules/terraform-ibm-icd-elasticsearch#198]
![image](https://github.com/terraform-ibm-modules/terraform-ibm-icd-elasticsearch/assets/10742925/fdb98004-e181-4d77-8e35-795aeb61abfc)

**Comment by shemau** [comment]
Support is being added in #184.

Note: The support does not fully remove that warning. It adds support for the new model where the warning will not be presented; without removing support for the old model, where the warning will still be generated.

It may be that the DA for example, being new, should be implemented to only accept the new model. So there may still be work to do under this issue.

**Comment by ocofaigh** [comment]
https://github.com/terraform-ibm-modules/terraform-ibm-icd-elasticsearch/releases/tag/v1.13.0
