### ISSUE TITLE
[Elasticsearch DA] Supporting documentation required for complex object type variables

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-icd-elasticsearch#205]
The below Elasticsearch DA variables are complex object types, and will be hard for consumers in Projects to know what format should be used for the values. I suggest that we add some supporting documentation for them, the same way we did [here](https://github.com/terraform-ibm-modules/terraform-ibm-kms-all-inclusive/blob/main/solutions/standard/DA-keys.md). Then we can update the variable descriptions to point to the supporting doc:

- `service_credential_names`
- `users`
- `auto_scaling`

**Comment by imprateeksh** [comment]
Changes are included in [PR-208](https://github.com/terraform-ibm-modules/terraform-ibm-icd-elasticsearch/pull/208)

**Comment by imprateeksh** [comment]
PR is merged hence closing the issue.
