### ISSUE TITLE
Elasticsearch DA variable updates

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-icd-elasticsearch#206]
- rename `existing_resource_group` -> `use_existing_resource_group` to be consistent with other DAs
- `elasticsearch_version` - since this has a default value, it means we need to maintain it. I suggest that we remove the default value, but make it a required variable in the ibm_catalog.json and have it so it has a dropdown list of the supported versions

**Comment by imprateeksh** [comment]
Started working on this issue.

**Comment by imprateeksh** [comment]
[PR-209](https://github.com/terraform-ibm-modules/terraform-ibm-icd-elasticsearch/pull/209) is created for this change and merged with [PR-208](https://github.com/terraform-ibm-modules/terraform-ibm-icd-elasticsearch/pull/208) to provide a single PR for all the related issues.

**Comment by imprateeksh** [comment]
PR merged hence closing the issue.
