### ISSUE TITLE
Rename the Elasticsearch DA flavor to `standard`

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-icd-elasticsearch#207]
- move code from `"solutions/secure"` -> `"solutions/standard"`
- update refs in ibm_catalog.json
- update variation in [.catalog-onboard-pipeline.yaml](https://github.com/terraform-ibm-modules/terraform-ibm-icd-elasticsearch/blob/main/.catalog-onboard-pipeline.yaml)

**Comment by imprateeksh** [comment]
Raised [PR-208](https://github.com/terraform-ibm-modules/terraform-ibm-icd-elasticsearch/pull/208). Will merge other related issues in the same PR.

**Comment by imprateeksh** [comment]
Two test failures are observed - 
1. `TestRunCompleteExampleOtherVersion`- Tried locally: [output_test.txt](https://github.com/user-attachments/files/16013938/output_test.txt)
2. Upgrade test failure is seen in PR pipeline - [TestRunStandardUpgradeTest](https://github.com/terraform-ibm-modules/terraform-ibm-icd-elasticsearch/actions/runs/9695898732/job/26756794053#step:7:176)

**Comment by imprateeksh** [comment]
PR merged, hence closing the issue.
