### ISSUE TITLE
Fix `users` variable to make `type` property optional as per documentation

### ISSUE THREAD

**Issue by imprateeksh** [terraform-ibm-modules/terraform-ibm-icd-elasticsearch#219]
The official documentation specifies that the user [type](https://registry.terraform.io/providers/IBM-Cloud/ibm/1.67.0/docs/resources/database#type) property within the `users` variable should be optional. 

Our current module configuration enforces the `type` property as a required field for each user object. This should be addressed to align with the documentation.

Currently, the users variable is defined as follows, making the type property required:
```hcl
variable "users" {
  type = list(object({
    name     = string
    password = string # pragma: allowlist secret
    type     = string # "type" is required to generate the connection string for the outputs.
    role     = optional(string)
  }))
}

```

**Comment by ocofaigh** [comment]
This should have been closed when https://github.com/terraform-ibm-modules/terraform-ibm-icd-elasticsearch/pull/226 was merged
