### ISSUE TITLE
Need ICD elasticsearch DA variation without KMS requirement and option to enable public endpoint

### ISSUE THREAD

**Issue by ajainghub** [terraform-ibm-modules/terraform-ibm-icd-elasticsearch#232]
The existing elasticsearch `standard` DA flavor/variation is secure by default and complies with fscloud requirements. It must use KMS encryption and exposes only private endpoints.

We need an elasticsearch `basic` DA variation that can provision elasticsearch without KMS encryption (i.e., uses IBM managed default encryption) and option to expose public endpoints.

We need this for use in the `basic` variation Gen AI RAG DA Stack where we don't have Key Protect. Reference: https://github.com/terraform-ibm-modules/terraform-ibm-icd-elasticsearch/issues/204

Also for reference 
https://github.com/terraform-ibm-modules/terraform-ibm-icd-elasticsearch/issues/224
https://github.com/terraform-ibm-modules/terraform-ibm-icd-elasticsearch/issues/225

**Comment by ocofaigh** [comment]
This is no longer required. Basic variation has Key Protect in it. Closing
