### ISSUE TITLE
ICD Elasticsearch DA needs option for setting reference to a pre-existing Elasticsearch instance

### ISSUE THREAD

**Issue by ajainghub** [terraform-ibm-modules/terraform-ibm-icd-elasticsearch#238]
In the current Elasticsearch DA there is no option to set references to an existing instance, i.e., we don't want to deploy a new instance again but set the reference to the existing instance (just like we are doing for pre-existing Secrets Manager instance). 
We need this feature for reusability of Elasticsearch instance - scenarios where multiple RAG DA Stacks can deploy artifacts,  (users,indexes/content etc.) to the same Elasticsearch instance.
Also reference: https://github.com/terraform-ibm-modules/terraform-ibm-icd-elasticsearch/issues/204
This will be additional Input option. Outputs will then include the information of the referenced instance.

**Comment by ocofaigh** [comment]
There is already an issue open for this https://github.com/terraform-ibm-modules/terraform-ibm-icd-elasticsearch/issues/235
