### ISSUE TITLE
 ELSER model should be enabled/true by default for Platinum edition

### ISSUE THREAD

**Issue by ajainghub** [terraform-ibm-modules/terraform-ibm-icd-elasticsearch#258]
When selecting and deploying Elasticsearch Platinum edition (e.g. in the RAG DA Stack), make ELSER model enabled/true by default.

Also please confirm the Elasticsearch DA deploys this elser model: `.elser_model_2_linux-x86_64`

**Comment by akocbek** [comment]
added in https://github.com/terraform-ibm-modules/dev-rag/pull/38
