### ISSUE TITLE
Elasticsearch plan usage costs in DA are inconsistent with Catalog

### ISSUE THREAD

**Issue by ajainghub** [terraform-ibm-modules/terraform-ibm-icd-elasticsearch#284]
Need clarity/correction on how the costs are calculated and shown on the Elasticsearch DA, compared to the what we see from Catalog, for Enterprise and Platinum plan configurations.

Also, when the Elasticsearch DA configuration is overridden for RAM, Disk and vCPU values, e.g in case of RAG DA Stack, the 
the costs should reflect the correct prices for provisioned  Enterprise plan and configuration ( 4GB RAM, 5GB Disk and 0.5 CPU ) x 3 members to match what is shown on the Catalog.
Per this link it seems if vCPU is set 0 it is adjusted to minimum 0.5 (https://cloud.ibm.com/docs/cloud-databases?topic=cloud-databases-hosting-models&interface=ui#shared-compute-placement)

**Comment by akocbek** [comment]
external bug: https://github.ibm.com/ibmcloud/CostEstimation/issues/386

**Comment by ocofaigh** [comment]
Fix was deployed
![image](https://github.com/user-attachments/assets/1c407c03-7373-4253-9209-c27a755b8d2d)
