### ISSUE TITLE
DA schematics test secret group name collision

### ISSUE THREAD

**Issue by shemau** [terraform-ibm-modules/terraform-ibm-icd-elasticsearch#335]
### Affected modules

The DA schematics test often fails to apply with

```hcl
 2024/11/12 15:40:00 Terraform apply |                   "message": "request_id: '50f98e42-c600-55c7-8794-8e33db983580' path: 'manage/v2/groups' operation: 'create' a secret group with name 'els-sr-da-secret-group' already exists. [secrets-manager.04126E]",
```

The resources create in SM, secret group name and secret name should be unique to the test run to avoid collision and unpredictably failures.

* terraform-ibm-icd-elasticsearch 

### Terraform CLI and Terraform provider versions

* Terraform version:
* Provider version:

### Steps to reproduce (including links and screen captures)

1. Run `terraform apply`

### Anything else

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by jor2** [comment]
https://github.com/terraform-ibm-modules/terraform-ibm-icd-elasticsearch/pull/330/files#diff-009e252987a2a3c3ea49bb0f9b3dc403769755965b5656e8b0a210d3499c0d6cR167
