### ISSUE TITLE
[terraform-ibm-icd-elasticsearch] add fix to exclude group from point in time recovery

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-icd-elasticsearch#344]
The same fix as https://github.com/terraform-ibm-modules/terraform-ibm-icd-postgresql/pull/525 is needed in Elasticsearch

**Comment by jor2** [comment]
https://github.com/terraform-ibm-modules/terraform-ibm-icd-elasticsearch/pull/330/files#diff-dc46acf24afd63ef8c556b77c126ccc6e578bc87e3aa09a931f33d9bf2532fbbR114
